image: macOS

# scripts that run after cloning repository
install:
  - ssh-keyscan github.com
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - brew install conan
  - conan install ../conanfile-unix.txt
  - cmake ..
  - make