image: macOS

# scripts that run after cloning repository
install:
  - mkdir -p ~/.ssh
  - touch ~/.ssh/known_hosts
  - ssh-keyscan github.com > ~/.ssh/known_hosts
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - brew install conan
  - conan install ../conanfile-unix.txt

build_script:
  - cmake ..
  - make