#include "ProjectSerializer.h"

#include <Engine/Core/EngineVersion.h>

#include <codecvt>
#include <fstream>
#include <yaml-cpp/emitter.h>

#define SHELL_ENGINE_EDITOR_VERSION "0.0.1"

namespace Shell {
    void ProjectSerializer::SerializeToFile(Project *project) {
        std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;

        YAML::Emitter out;
        out << YAML::Comment("This file is automatically generated by the editor, do not modify it!");
        out << YAML::BeginMap;
        out << YAML::Key << "Shell-Version";
        out << YAML::Value << SHELL_ENGINE_VERSION;
        out << YAML::Key << "Shell-Editor-Version";
        out << YAML::Value << SHELL_ENGINE_EDITOR_VERSION;
        out << YAML::Key << "Project-Name";
        out << YAML::Value << converter.to_bytes(project->GetName());
        out << YAML::EndMap;

        auto projectFilePath = project->GetPath() / "project.yml";
        std::ofstream projectFile(projectFilePath);
        projectFile << out.c_str();
    }
}