#include "SceneSerializer.h"

#include <codecvt>
#include <fstream>
#include <yaml-cpp/yaml.h>

namespace Shell::Editor {
    void SceneSerializer::SerializeToFile(const std::filesystem::path &path, const Ref<SceneBlueprint>& sceneBlueprint) {

        YAML::Emitter out;
        out << YAML::Comment("This file is automatically generated by the editor, do not modify it!");
        out << YAML::BeginMap;

        out << YAML::Key << "Name";
        out << YAML::Value << sceneBlueprint->GetName();

        out << YAML::EndMap;

        std::ofstream projectFile(path);
        projectFile << out.c_str();
    }

    Ref <SceneBlueprint> SceneSerializer::DeserializeFromFile(const std::filesystem::path &path) {
        return Shell::Ref<SceneBlueprint>();
    }
}